Create DATABASE navidad;
use navidad;
CREATE TABLE participantes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) UNIQUE NOT NULL,
  asignado_id INT NULL,
  seleccionado BOOLEAN DEFAULT FALSE
);
INSERT INTO participantes (nombre) VALUES
('SANDRA PATRICIA HUELGOS CASAS'),
('JEIMY MARCELA RAMIREZ'),
('JULIAN MELENDEZ'),
('MATEO SANCHEZ '),
('MARTIN MELENDEZ'),
('JEISON DAVID RAMIREZ'),
('ELVIA ROCIO HUELGOS CASAS'),
('FELIPE VARGAS'),
('ANGELICA AYALA'),
('JULIETA VARGAS'),
('ANDRES VARGAS'),
('GISEL ANDREA HUELGOS CASAS'),
('LUIS ALBERTO MAHECHA'),
('LUIS ALEJANDRO MAHECHA'),
('VIVIANA CARDOZO'),
('PAULA JARAMILLO'),
('ABIGAIL CASAS'),
('ALCIBIADES MORALES');

